---
- hosts: test
  tasks:
  - name: Ansible register variable basic example
    shell: "find *.txt"
    args:
      chdir: "/opt/"
    register: find_output
  - debug:
      var: find_output
  - shell: "cp {{ item }} {{item}}_bkp"
    args:
      chdir: "/opt/"
    with_items:
      - "{{ find_output.stdout_lines }}"
...
